language: node_js
node_js: '14.1.0'

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libsecret-1-dev

before_script:
  - npm install
  - npm run parse

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

branches:
  only:
    - master

git:
  depth: 10

notifications:
  email:
    on_success: change
    on_failure: change
